### ISSUE TITLE
LocalAuthority used when reading XML documents

### ISSUE THREAD

**Issue by pdowler** [opencadc/ac#10]
the abstract reader class uses LocalAuthority to mangle group URIs while reading docs; it should not need it at all and should just construct the group as transmitted... if full URIs are missing then doc format has to change.... I suggest changing the model to start using the GroupURI class if possible since it will help uncover the inconsistent use of "String group" which sometimes is a URI and sometimes just the name.

**Comment by brianmajor** [comment]
The changes were addressed in a pull request from branch "issue-10".
Groups now use a the GroupURI object for identification.
