### ISSUE TITLE
Cookies created by cadc-access-control-server are not RFC compliant

### ISSUE THREAD

**Issue by brianmajor** [opencadc/ac#50]
The cookies generated by the login endpoint contain characters that are not accepted by the most recent versions of apache tomcat.  

The workaround is to have tomcat use a legacy cookie processor by adding the following directive to context.xml:

`<CookieProcessor className="org.apache.tomcat.util.http.LegacyCookieProcessor" />`

**Comment by at88mph** [comment]
The current cookie format looks like:
expirytime=`EXPIRYTIME`&X500=`DISTINGUISHED_NAME_IDENTITY`&numericID=`NUMERIC_IDENTITY`&userID=`HTTP_USERNAME_IDENTITY`&scope=`SCOPE`&domain=`DOMAINS[]`&signature=`ENCODED_SIGNATURE`

Is the correct solution to remove the identities values and have them encoded in the signature?

**Comment by brianmajor** [comment]
It is simply to encode them, not to add them to the signature.  The
signature should be a string created from the value of the cookie (soon to
be encoded) that uses the private key.  I think base64 would be a suitable
encoding for the value of the cookie.

**Comment by at88mph** [comment]
Pull Request #57 issued in `opencadc/core`:
https://github.com/opencadc/core/pull/57
